branch-defaults:
  default:
    environment: RecipeWebApp
global:
  application_name: RecipeWebApp
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: null
